[package]
name = "zerozen"
version = "1.0.0"
edition = "2021"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[dependencies]

anyhow = "1.0.98"
image = "0.25.6"
rand = "0.9.1"
rand_distr = "0.5.1"
